# Generated by Django 2.1.3 on 2019-01-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190121_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='liquid',
        ),
        migrations.RemoveField(
            model_name='item',
            name='bottles',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='bottle',
            name='owner_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bottle',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='liquid',
            field=models.ManyToManyField(to='employee.Liquid'),
        ),
        migrations.AddField(
            model_name='liquid',
            name='bottle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee.Bottle'),
            preserve_default=False,
        ),
    ]
