# Generated by Django 2.1.3 on 2019-01-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20190121_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquid',
            name='bottle',
        ),
        migrations.AddField(
            model_name='liquid',
            name='bottle',
            field=models.ManyToManyField(to='employee.Bottle'),
        ),
    ]
