# Generated by Django 2.1.3 on 2019-01-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20190121_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquid',
            name='bottle',
        ),
        migrations.AddField(
            model_name='liquid',
            name='strength',
            field=models.CharField(default='20', max_length=8),
        ),
        migrations.AddField(
            model_name='liquid',
            name='volume',
            field=models.CharField(default='10', max_length=8),
        ),
    ]
