# Generated by Django 2.1.3 on 2019-01-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20190121_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='items',
        ),
        migrations.AddField(
            model_name='inventory',
            name='items',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee.Item'),
            preserve_default=False,
        ),
    ]
