# Generated by Django 2.1.3 on 2019-01-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20190121_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='items',
        ),
        migrations.AddField(
            model_name='inventory',
            name='items',
            field=models.ManyToManyField(to='employee.Item'),
        ),
    ]
