# Generated by Django 2.1.3 on 2019-01-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20190121_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquid',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='liquid',
            name='volume',
        ),
        migrations.AddField(
            model_name='item',
            name='strength',
            field=models.CharField(default='20', max_length=8),
        ),
        migrations.AddField(
            model_name='item',
            name='volume',
            field=models.CharField(default='10', max_length=8),
        ),
        migrations.AlterField(
            model_name='solditems',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
