# Generated by Django 2.1.3 on 2019-01-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSoldItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('taste', models.CharField(max_length=255)),
                ('is_nic_salt', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1)),
                ('volume', models.CharField(default='10', max_length=8)),
                ('strength', models.CharField(default='20', max_length=8)),
            ],
        ),
    ]
