# Generated by Django 2.1.3 on 2019-01-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsolditems',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
